spring:
  datasource:
    url: jdbc:h2:mem:database
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  kafka:
    bootstrap-servers: localhost:9092

token:
  secretKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
  validityInMilliseconds: 3600000

payment:
  secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  password: ':'

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: health,info,prometheus,circuitbreakers
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 60
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException
          - roomescape.payment.client.exception.PaymentInfrastructureException
          - roomescape.payment.client.exception.PaymentProviderException
        ignoreExceptions:
          - roomescape.payment.client.exception.PaymentBusinessException
          - roomescape.payment.client.exception.PaymentClientException
          - roomescape.payment.client.exception.PaymentPolicyException
          - roomescape.payment.client.exception.PaymentStateException

    instances:
      default-pg:
        baseConfig: default
      toss-payment:
        baseConfig: default

logging:
  level:
    org.springframework.transaction.interceptor: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
